### ISSUE TITLE
Can't find habitat-lab submodule

### ISSUE THREAD

**Issue by mbowcut2** [yashkant/housekeep#1]
following the build instructions in the README, and I can't find the habitat-lab repo. Looks like you removed it? How do I proceed in using the sim?

**Comment by yvsriram** [comment]
Thank you for pointing this out! The submodules should be updated now. Please retry the instructions in the README.

Edit: I realised that the habitat-lab commits we are using are not public yet. We will make them public soon!

**Comment by yashkant** [comment]
Thanks for the issue, I made the repo public, let us know if doesn't work now.
