### ISSUE TITLE
Missing File global_mapping_v3.yaml

### ISSUE THREAD

**Issue by karan-13-hub** [yashkant/housekeep#3]
FileNotFoundError: [Errno 2] No such file or directory: 'cos_eor/utils/dump_archive/global_mapping_v3.yaml'
There is no folder called dump_archive in the path mentioned. Please add the above folder with all the required files.

**Comment by yashkant** [comment]
Hi @karan-13-hub,

Thanks for checking out housekeep. Could you tell us more of where this error was triggered?

**Comment by yashkant** [comment]
closing for now, but feel free to reopen.
